services:
  api:
    image: sampleboi-api
    build: ./api
    volumes:
      - ./api:/app
      - /app/__pypackages__
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db
  frontend:
    image: sampleboi-ui
    build: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - 5173:5173
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 6543:5432
