services:
  backend:
    image: sampleboi-backend
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/__pypackages__
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db
  frontend:
    image: sampleboi-frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 6543:5432
