services:
  backend:
    image: sampleboi-backend
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/__pypackages__
    ports:
      - 80:80
  frontend:
    image: sampleboi-frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
  db:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb"
