services:
  api:
    image: sampleboi-api
    env_file:
      - ./api/.env.dev
    build: ./api
    volumes:
      - ./api:/app
      - /app/__pypackages__
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db
  ui:
    image: sampleboi-ui
    build: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - 5173:5173
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
      - POSTGRES_USER=user
    ports:
      - 6543:5432
volumes:
  postgres_data:
