version: 1
disable_existing_loggers: False
filters:
  healthcheck_filter:
    "()": config.HealthCheckFilter
formatters:
  simple:
    format: '%(levelname)s %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        filters:
            - healthcheck_filter
        stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
